### ISSUE TITLE
请问IK分词器支持ARM64架构下的ES吗？支持的话，是从哪个版本开始？

### ISSUE THREAD

**Issue by lixiang12345** [infinilabs/analysis-ik#1004]

**Comment by luyang-yanglu** [comment]
同问：
Exception in thread "main" java.lang.IllegalStateException: Plugin [.installing-15744301235713118090] is missing a descriptor properties file.
        at org.elasticsearch.plugins.PluginDescriptor.readFromProperties(PluginDescriptor.java:199)
        at org.elasticsearch.plugins.PluginsUtils.readPluginBundle(PluginsUtils.java:185)
        at org.elasticsearch.plugins.PluginsUtils.findBundles(PluginsUtils.java:166)
        at org.elasticsearch.plugins.PluginsUtils.getPluginBundles(PluginsUtils.java:148)
        at org.elasticsearch.plugins.PluginsUtils.preInstallJarHellCheck(PluginsUtils.java:217)
        at org.elasticsearch.plugins.cli.InstallPluginAction.jarHellCheck(InstallPluginAction.java:910)
        at org.elasticsearch.plugins.cli.InstallPluginAction.loadPluginInfo(InstallPluginAction.java:872)
        at org.elasticsearch.plugins.cli.InstallPluginAction.installPlugin(InstallPluginAction.java:918)
        at org.elasticsearch.plugins.cli.InstallPluginAction.execute(InstallPluginAction.java:254)
        at org.elasticsearch.plugins.cli.InstallPluginCommand.execute(InstallPluginCommand.java:89)
        at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:54)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:94)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
        at org.elasticsearch.cli.Command.main(Command.java:50)
        at org.elasticsearch.launcher.CliToolLauncher.main(CliToolLauncher.java:64)

**Comment by kin122** [comment]
@lixiang12345 @luyang-yanglu  IK 是纯 Java 插件，只要 ES 的版本能支持 ARM 架构就可以。 ES 版本 >= 7.8.0，就支持arm了
https://www.elastic.co/blog/elasticsearch-on-arm
