### ISSUE TITLE
Failed installing IK

### ISSUE THREAD

**Issue by vegetablest** [infinilabs/analysis-ik#1066]
I used ECK to install ES on k8s and installed the `IK` in the init container, but it failed. 

<details>
<summary>The configuration</summary>

```yml
      initContainers:
      - name: install-plugins
        command:
        - sh
        - -c
        - |
          bin/elasticsearch-plugin install --batch https://get.infini.cloud/elasticsearch/analysis-ik/8.14.1
      containers:
      - name: elasticsearch 
```

</details>
<details>
<summary>Error messages</summary>

-> Installing https://get.infini.cloud/elasticsearch/analysis-ik/8.12.2
-> Downloading https://get.infini.cloud/elasticsearch/analysis-ik/8.12.2
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.net.SocketPermission * connect,resolve
See https://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
-> Failed installing https://get.infini.cloud/elasticsearch/analysis-ik/8.12.2
-> Rolling back https://get.infini.cloud/elasticsearch/analysis-ik/8.12.2
-> Rolled back https://get.infini.cloud/elasticsearch/analysis-ik/8.12.2
Exception in thread "main" java.nio.file.FileSystemException: /usr/share/elasticsearch/config/analysis-ik: Operation not permitted
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setOwners(UnixFileAttributeViews.java:291)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setOwner(UnixFileAttributeViews.java:313)
	at org.elasticsearch.plugins.cli.InstallPluginAction.setOwnerGroup(InstallPluginAction.java:1077)
	at org.elasticsearch.plugins.cli.InstallPluginAction.installConfig(InstallPluginAction.java:1051)
	at org.elasticsearch.plugins.cli.InstallPluginAction.installPluginSupportFiles(InstallPluginAction.java:974)
	at org.elasticsearch.plugins.cli.InstallPluginAction.installPlugin(InstallPluginAction.java:943)
	at org.elasticsearch.plugins.cli.InstallPluginAction.execute(InstallPluginAction.java:254)
	at org.elasticsearch.plugins.cli.InstallPluginCommand.execute(InstallPluginCommand.java:89)
	at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:94)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
	at org.elasticsearch.cli.Command.main(Command.java:50)
	at org.elasticsearch.launcher.CliToolLauncher.main(CliToolLauncher.java:64)
</details>

**Comment by NanMu93** [comment]
`        - name: install-plugins
          securityContext:
            privileged: true
            runAsUser: 0
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch https://get.infini.cloud/elasticsearch/analysis-ik/8.14.1`
grant root privileges.

**Comment by NanMu93** [comment]
> > ```
> >         - name: install-plugins
> >           securityContext:
> >              privileged: true
> >              runAsUser: 0
> >           command:
> >           - sh
> >           - -c
> >           - |
> >             bin/elasticsearch-plugin install --batch https://get.infini.cloud/elasticsearch/analysis-ik/8.14.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > grant root privileges.
> > runAsUser: 1000 ?

runAsUser:  0
