### ISSUE TITLE
mvn package failed for elasticsearch-analysis-ik-master

### ISSUE THREAD

**Issue by ApprenticeMythology** [infinilabs/analysis-ik#347]
hi
After download elasticsearch-analysis-ik-master.zip and unzip it.
i use mvn package to build it.
mvn vertion:
wanglf@wanglf:/usr/local/elasticsearch$ mvn -V
Apache Maven 2.2.1 (rdebian-14)
Java version: 1.8.0_121
Java home: /usr/local/java/jdk1.8.0_121/jre
Default locale: en_US, platform encoding: UTF-8

but i met a problem below, please help check what the problem is~~~
wanglf@wanglf:~/webServer/depend_plugin/elasticsearch-analysis-ik-master$ mvn package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).

Project ID: org.elasticsearch:elasticsearch-analysis-ik:jar:${elasticsearch.version}

Reason: Cannot find parent: org.sonatype.oss:oss-parent for project: org.elasticsearch:elasticsearch-analysis-ik:jar:${elasticsearch.version} for project org.elasticsearch:elasticsearch-analysis-ik:jar:${elasticsearch.version}

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.reactor.MavenExecutionException: Cannot find parent: org.sonatype.oss:oss-parent for project: org.elasticsearch:elasticsearch-analysis-ik:jar:${elasticsearch.version} for project org.elasticsearch:elasticsearch-analysis-ik:jar:${elasticsearch.version}
at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:404)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:272)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.project.ProjectBuildingException: Cannot find parent: org.sonatype.oss:oss-parent for project: org.elasticsearch:elasticsearch-analysis-ik:jar:${elasticsearch.version} for project org.elasticsearch:elasticsearch-analysis-ik:jar:${elasticsearch.version}
at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1396)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildInternal(DefaultMavenProjectBuilder.java:823)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFileInternal(DefaultMavenProjectBuilder.java:508)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:200)
at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:604)
at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:487)
at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:391)
... 12 more
Caused by: org.apache.maven.project.InvalidProjectModelException: Not a v4.0.0 POM. for project org.sonatype.oss:oss-parent at /home/wanglf/.m2/repository/org/sonatype/oss/oss-parent/9/oss-parent-9.pom
at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjectBuilder.java:1599)
at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjectBuilder.java:1571)
at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:562)
at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1392)
... 18 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Tue Mar 21 17:14:28 EDT 2017
[INFO] Final Memory: 2M/57M
[INFO] ------------------------------------------------------------------------

**Comment by sam2099** [comment]
org.sonatype.oss:oss-parent 这个工程估计没下载到你本地

**Comment by hufuman** [comment]
Try: mvn package -U
maybe some error happened when mvn download sonatype.oss
