### ISSUE TITLE
win下安装完ik，启动es报错

### ISSUE THREAD

**Issue by fanruohongclub** [infinilabs/analysis-ik#793]
future versions of Elasticsearch will require Java 11; your Java version from [C:\Program Files\Java\jdk1.8.0_171\jre] does not meet this requirement
Warning: with JDK 8 on Windows, Elasticsearch may be unable to derive correct
  ergonomic settings due to a JDK issue (JDK-8074459). Please use a newer
  version of Java.
Warning: MaxDirectMemorySize may have been miscalculated due to JDK-8074459.
  Please use a newer version of Java or set MaxDirectMemorySize explicitly.
[2020-06-12T19:13:36,684][INFO ][o.e.e.NodeEnvironment    ] [DESKTOP-N5SEG76] using [1] data paths, mounts [[(E:)]], net usable_space [793.4gb], net total_space [931.4gb], types [NTFS]
[2020-06-12T19:13:36,686][INFO ][o.e.e.NodeEnvironment    ] [DESKTOP-N5SEG76] heap size [989.8mb], compressed ordinary object pointers [true]
[2020-06-12T19:13:36,953][INFO ][o.e.n.Node               ] [DESKTOP-N5SEG76] node name [DESKTOP-N5SEG76], node ID [A4ULpwwwQSa74Tf5NXC6Lg], cluster name [elasticsearch]
[2020-06-12T19:13:36,954][INFO ][o.e.n.Node               ] [DESKTOP-N5SEG76] version[7.6.2], pid[25724], build[default/zip/ef48eb35cf30adf4db14086e8aabd07ef6fb113f/2020-03-26T06:34:37.794943Z], OS[Windows 10/10.0/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_171/25.171-b11]
[2020-06-12T19:13:36,954][INFO ][o.e.n.Node               ] [DESKTOP-N5SEG76] JVM home [C:\Program Files\Java\jdk1.8.0_171\jre]
[2020-06-12T19:13:36,955][INFO ][o.e.n.Node               ] [DESKTOP-N5SEG76] JVM arguments [-Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=COMPAT, -Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Djava.io.tmpdir=C:\Users\15658\AppData\Local\Temp\elasticsearch, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -XX:+PrintTenuringDistribution, -XX:+PrintGCApplicationStoppedTime, -Xloggc:logs/gc.log, -XX:+UseGCLogFileRotation, -XX:NumberOfGCLogFiles=32, -XX:GCLogFileSize=64m, -XX:MaxDirectMemorySize=536870912, -Delasticsearch, -Des.path.home=E:\ProgramSoftware\ES\elasticsearch-7.6 2\elasticsearch-7.6.2, -Des.path.conf=E:\ProgramSoftware\ES\elasticsearch-7.6 2\elasticsearch-7.6.2\config, -Des.distribution.flavor=default, -Des.distribution.type=zip, -Des.bundled_jdk=true]
[2020-06-12T19:13:37,037][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [DESKTOP-N5SEG76] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Could not load plugin descriptor for plugin directory [analysis-ik]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:174) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125) ~[elasticsearch-cli-7.6.2.jar:7.6.2]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.6.2.jar:7.6.2]
Caused by: java.lang.IllegalStateException: Could not load plugin descriptor for plugin directory [analysis-ik]
        at org.elasticsearch.plugins.PluginsService.readPluginBundle(PluginsService.java:401) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.plugins.PluginsService.findBundles(PluginsService.java:386) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:379) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:151) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.node.Node.<init>(Node.java:313) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.node.Node.<init>(Node.java:257) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.6.2.jar:7.6.2]
        ... 6 more
Caused by: java.nio.file.NoSuchFileException: E:\ProgramSoftware\ES\elasticsearch-7.6 2\elasticsearch-7.6.2\plugins\analysis-ik\plugin-descriptor.properties
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102) ~[?:?]
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230) ~[?:?]
        at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_171]
        at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_171]
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384) ~[?:1.8.0_171]
        at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_171]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:156) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.plugins.PluginsService.readPluginBundle(PluginsService.java:398) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.plugins.PluginsService.findBundles(PluginsService.java:386) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:379) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:151) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.node.Node.<init>(Node.java:313) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.node.Node.<init>(Node.java:257) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.6.2.jar:7.6.2]
        ... 6 more
uncaught exception in thread [main]
java.lang.IllegalStateException: Could not load plugin descriptor for plugin directory [analysis-ik]
Likely root cause: java.nio.file.NoSuchFileException: E:\ProgramSoftware\ES\elasticsearch-7.6 2\elasticsearch-7.6.2\plugins\analysis-ik\plugin-descriptor.properties
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:156)
        at org.elasticsearch.plugins.PluginsService.readPluginBundle(PluginsService.java:398)
        at org.elasticsearch.plugins.PluginsService.findBundles(PluginsService.java:386)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:379)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:151)
        at org.elasticsearch.node.Node.<init>(Node.java:313)
        at org.elasticsearch.node.Node.<init>(Node.java:257)
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
For complete error details, refer to the log at E:\ProgramSoftware\ES\elasticsearch-7.6 2\elasticsearch-7.6.2\logs\elasticsearch.log

**Comment by JustinBaoLin** [comment]
你这ik下载的是source code吧？
![image](https://user-images.githubusercontent.com/74496070/104400400-66e58680-558d-11eb-8dc6-e3e95fa12600.png)
这是解压后的文件目录结构：
![image](https://user-images.githubusercontent.com/74496070/104400506-8aa8cc80-558d-11eb-84f9-c0e604bc1eb7.png)
